routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'QuestionsController@index');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('questions','QuestionsController')->except('show');

Route::resource('questions.answers','AnswersController')->except('show','create');

Route::get('/questions/{slug}','QuestionsController@show')->name('questions.show');

Route::post('/answers/{answer}/accept','AcceptAnswerController')->name('answers.accept');

Route::post('/questions/{question}/favorites','FavoritesController@store')->name('questions.favorite');

Route::delete('/questions/{question}/favorites','FavoritesController@destroy')->name('questions.unfavorite');

Route::post('/questions/{question}/vote','VoteQuestionController');

Route::post('/answers/{answer}/vote','VoteAnswerController');

app/Answer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\User;
use App\Question;
class Answer extends Model
{
    use VotableTrait;
    protected $fillable = ['user_id','body'];
    protected $appends = ['created_date','body_html','is_best'];
    public function question(){
        return $this->belongsTo(Question::class);
    }
    public function user(){
        return $this->belongsTo(User::class);
    }
    public function getBodyHtmlAttribute(){
        return \Parsedown::instance()->text($this->body);
    }
    public static function boot(){
        parent::boot();

        static::created(function($answer){
            $answer->question->increment('answers_count');
        });
        
        static::deleted(function($answer){
            $question = $answer->question;
            $question->decrement('answers_count');
            if($question->best_answer_id == $answer->id){
                $question->best_answer_id = NULL;
                $question->save();
            }
        });
    }
    public function getCreatedDateAttribute(){
        return $this->created_at->diffForHumans();
    }
    public function getStatusAttribute(){
        return $this->isBest()?'vote-accepted':'';
    }
    public function getIsBestAttribute(){
        return $this->isBest();
    }
    public function isBest(){
        return $this->id == $this->question->best_answer_id;
    }
    
}

app/Http/Controllers/AnswersController.php
<?php

namespace App\Http\Controllers;

use App\Answer;
use Illuminate\Http\Request;
use App\Question;
use Illuminate\Support\Facades\Gate;

class AnswersController extends Controller
{
    
    public function __construct(){
        $this->middleware('auth')->except('index');
    }
    public function index(Question $question){
        return $question->answers()->with('user')->simplePaginate(3);
    }
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Question $question,Request $request)
    {
        // $request->validate([
        //     'body'=>'required'
        // ]);

       $answer =  $question->answers()->create(['body'=>$request->body,'user_id'=>\Auth::id()]);

        if($request->expectsJson()){
            return response()->json([
                'message'=>'Your answer has been submitted succesfully',
                'answer' => $answer->load('user')
            ]);
        }
        //return back()->with('success','Your answer has been submitted succesfully');
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Answer  $answer
     * @return \Illuminate\Http\Response
     */
    public function edit(Question $question,Answer $answer)
    {
        if(Gate::allows('update-answer',$answer)){
            return view("answers.edit",compact('question','answer'));
        };
        abort(403,"Access denied");
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Answer  $answer
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Question $question,Answer $answer)
    {
        if(Gate::allows('update-answer',$answer)){
            $answer->update($request->validate([
                'body'=>'required',
            ]));
            
            if($request->expectsJson()){
                return response()->json([
                    'message' =>'Your question has been updated',
                    'body_html'=>$answer->body_html
                ]);
            }
            
            //return redirect()->route('questions.show',$question->slug)->with('success','Your question has been updated');
        };
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Answer  $answer
     * @return \Illuminate\Http\Response
     */
    public function destroy(Question $question,Answer $answer,Request $request)
    {
        if(Gate::allows('delete-answer',$answer)){
            $answer->delete();
            if($request->expectsJson()){
                return response()->json([
                    'message' =>'Your answer has been removed',
                ]);
            }
            //return redirect()->route('questions.show',$question->slug)->with('success',"Your message has been deleted");
            return back()->with('success','Your answer has been removed');
        };

        abort(403,"Access denied");
    }
}

resources/views/answers/_answer.blade.php
<answer :answer="{{$answer}}" inline-template>
    
</answer>

resources/views/answers/_index.blade.php
@if ($answersCount>0)
    <div class="row mt-4" v-cloak>
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <div class="card-title">
                        <h2>{{ $answersCount . " " . str_plural('Answer', $answersCount) }}</h2>
                    </div>
                    <hr>
                    @include('layouts._messages')
                    @foreach ($answers as $answer)
                        @include ('answers._answer') 
                    @endforeach
                </div>
            </div>
        </div>
    </div>
@endif

resources/views/answers/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row mt-4">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <div class="card-title">
                        <h3>Editing Answer for question: <strong>{{$question->title}}</strong></h3>
                    </div>
                    <hr>
                    <form action="{{route('questions.answers.update',[$question->id,$answer->id])}}" method="post">
                        @csrf
                        @method('PATCH')
                        <div class="form-group">
                            <textarea class="form-control {{$errors->has('body')?'is-invalid':''}}" rows="7" name="body">{{old('body',$answer->body)}}</textarea>
                            @if ($errors->has('body'))
                                <div class="ivalid-feedback">
                                    <strong>{{$errors->first('body')}}</strong>
                                </div>
                            @endif
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-lg btn-outline-primary">Update</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection